version: 2
jobs:
  build:

    working_directory: ~/shopify

    docker:
      - image: circleci/openjdk:8-jdk-browsers
      - image: circleci/mysql:5.7
        environment:
          MYSQL_DATABASE: db_shopify
          MYSQL_USER: root
          MYSQL_PASSWORD: root
        ports:
          - 3306:3306

    steps:

      - checkout

      - run: mvn dependency:go-offline

      - run:
          name: Install MySQL CLI; Import dummy data; run an example query
          command: |
            sudo apt-get install mysql-client
            mysql -h 127.0.0.1 -u root -p root db_shopify

      - run: mvn package
